# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build with Maven
        run: mvn --batch-mode package

      - name: Unit Tests
        run: mvn --batch-mode test

      - name: Prepare Artifact
        run: |
          TAG_NAME=${{github.event.release.tag_name}}
          VERSION=$(echo $TAG_NAME | sed -e 's/v\(.*\)/\1/')
          echo "choralVersion=$VERSION" >> $GITHUB_ENV
          unzip "dist/target/choral-$VERSION" -d "dist/target/choral-$VERSION"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: choral-${{env.choralVersion}}
          path: dist/target/choral-${{env.choralVersion}}/*

      - name: Publish package
        run: mvn -P release --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
