# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Unit Tests
      run: mvn test --file pom.xml

    - name: Prepare Artifact
      run: |
        TAG_NAME=${{github.event.release.tag_name}}
        VERSION=$(echo $TAG_NAME | sed -e 's/v\(.*\)/\1/')
        echo "choralVersion=$VERSION" >> $GITHUB_ENV
        unzip "dist/target/choral-$VERSION" -d "dist/target/choral-$VERSION"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: choral-${{env.choralVersion}}
        path: dist/target/choral-${{env.choralVersion}}/*

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
